### ISSUE TITLE
peerDependency issue with unexpected-react ~1.0.0

### ISSUE THREAD

**Issue by cthorner** [sapegin/expect-react-shallow#3]
I'm trying to upgrade to React 15, but looks like expect-react-shallow has a dependency on unexpected-react 1.0.0 (patch level depedency) which has a peerDependency on react 0.14(minor dependency).

Latest version of unexpected-react fixes the issue(version 3.2.3)

**Comment by sapegin** [comment]
Could you please submit a pull request with a fix?

**Comment by cthorner** [comment]
Sure

**Comment by cthorner** [comment]
#4 created. I had to add react-dom to peerDependencies as well, as unexpected-react now uses it for findDOMNode and expects it as a peerDependency. Also, maybe a bit presumptive I upped the patch level version to 1.2.1 to make it easier to tag and release, let me know if you want me to remove that. Also upgraded react-addons-test-utils and allowed the tests to run on the latest version of react, so I could make sure they still passed if anyone is using v15.1.

**Comment by sapegin** [comment]
Thank you very much!

> I upped the patch level version to 1.2.1 to make it easier to tag and release

It actually makes it harder because I use a script to make releases ;-)

**Comment by cthorner** [comment]
Ok, no problem. I'll remove it. 👍
